// 二年级语文 - 识字表（会认的字）
// 人教版 - 上下学期完整数据

const grade2ChineseShizibiao = {
    // 上学期数据（完整）
    semester1: [
        // 第一单元
        // 第1课《小蝌蚪找妈妈》
        { character: '塘', pinyin: 'táng', type: 'character', example: '池塘里有一群小蝌蚪。', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        { character: '脑', pinyin: 'nǎo', type: 'character', example: '大大的脑袋，黑灰色的身子。', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        { character: '袋', pinyin: 'dài', type: 'character', example: '大大的脑袋，黑灰色的身子。', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        { character: '灰', pinyin: 'huī', type: 'character', example: '黑灰色的身子。', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        { character: '活', pinyin: 'huó', type: 'character', example: '快活地游来游去。', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        { character: '哇', pinyin: 'wā', type: 'character', example: '小蝌蚪游哇游，过了几天，长出了两条后腿。', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        { character: '教', pinyin: 'jiāo', type: 'character', example: '他们看见鲤鱼妈妈在教小鲤鱼捕食。', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        { character: '捕', pinyin: 'bǔ', type: 'character', example: '在教小鲤鱼捕食。', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        { character: '迎', pinyin: 'yíng', type: 'character', example: '小蝌蚪就迎上去。', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        { character: '阿', pinyin: 'ā', type: 'character', example: '鲤鱼阿姨，我们的妈妈在哪里？', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        { character: '姨', pinyin: 'yí', type: 'character', example: '鲤鱼阿姨，我们的妈妈在哪里？', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        { character: '宽', pinyin: 'kuān', type: 'character', example: '你们的妈妈四条腿，宽嘴巴。', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        { character: '龟', pinyin: 'guī', type: 'character', example: '他们看见一只乌龟摆动着四条腿。', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        { character: '连', pinyin: 'lián', type: 'character', example: '小蝌蚪连忙追上去。', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        { character: '披', pinyin: 'pī', type: 'character', example: '披着绿衣裳。', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        { character: '鼓', pinyin: 'gǔ', type: 'character', example: '鼓着一对大眼睛。', lesson: '第1课', lessonName: '小蝌蚪找妈妈', unit: '第一单元', semester: 1 },
        
        // 第2课《我是什么》
        { character: '汽', pinyin: 'qì', type: 'character', example: '太阳一晒，我就变成汽。', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        { character: '袍', pinyin: 'páo', type: 'character', example: '早晨和傍晚我又把红袍披在身上。', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        { character: '越', pinyin: 'yuè', type: 'character', example: '我在空中越升越高。', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        { character: '温', pinyin: 'wēn', type: 'character', example: '体温越来越低。', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        { character: '滴', pinyin: 'dī', type: 'character', example: '变成了无数小水滴。', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        { character: '奔', pinyin: 'bēn', type: 'character', example: '在江河里奔跑。', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        { character: '洋', pinyin: 'yáng', type: 'character', example: '在海洋里跳舞。', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        { character: '发', pinyin: 'fā', type: 'character', example: '发动机器，帮助人们工作。', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        { character: '器', pinyin: 'qì', type: 'character', example: '发动机器，帮助人们工作。', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        { character: '淹', pinyin: 'yān', type: 'character', example: '淹没庄稼，冲毁房屋。', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        { character: '没', pinyin: 'mò', type: 'character', example: '淹没庄稼，冲毁房屋。', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        { character: '庄', pinyin: 'zhuāng', type: 'character', example: '淹没庄稼。', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        { character: '稼', pinyin: 'jià', type: 'character', example: '淹没庄稼。', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        { character: '屋', pinyin: 'wū', type: 'character', example: '冲毁房屋。', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        { character: '灾', pinyin: 'zāi', type: 'character', example: '给人们带来灾害。', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        { character: '猜', pinyin: 'cāi', type: 'character', example: '小朋友，你们猜猜，我是什么？', lesson: '第2课', lessonName: '我是什么', unit: '第一单元', semester: 1 },
        
        // 第3课《植物妈妈有办法》
        { character: '植', pinyin: 'zhí', type: 'character', example: '植物妈妈有办法。', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        { character: '如', pinyin: 'rú', type: 'character', example: '孩子如果已经长大。', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        { character: '旅', pinyin: 'lǚ', type: 'character', example: '植物旅行又用什么办法？', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        { character: '准', pinyin: 'zhǔn', type: 'character', example: '蒲公英妈妈准备了降落伞。', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        { character: '备', pinyin: 'bèi', type: 'character', example: '蒲公英妈妈准备了降落伞。', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        { character: '送', pinyin: 'sòng', type: 'character', example: '把它送给自己的娃娃。', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        { character: '分', pinyin: 'fēn', type: 'character', example: '孩子们就乘着风纷纷出发。', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        { character: '挂', pinyin: 'guà', type: 'character', example: '只要挂住动物的皮毛。', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        { character: '挺', pinyin: 'tǐng', type: 'character', example: '石榴妈妈的胆子挺大。', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        { character: '钻', pinyin: 'zuān', type: 'character', example: '就会钻出来落户安家。', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        { character: '底', pinyin: 'dǐ', type: 'character', example: '她让豆荚晒在太阳底下。', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        { character: '炸', pinyin: 'zhà', type: 'character', example: '豆荚炸开。', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        { character: '离', pinyin: 'lí', type: 'character', example: '孩子们就蹦着跳着离开妈妈。', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        { character: '识', pinyin: 'shí', type: 'character', example: '那里有许许多多的知识。', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        { character: '粗', pinyin: 'cū', type: 'character', example: '粗心的小朋友却得不到它。', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        { character: '得', pinyin: 'dé', type: 'character', example: '却得不到它。', lesson: '第3课', lessonName: '植物妈妈有办法', unit: '第一单元', semester: 1 },
        
        // 语文园地一
        { character: '朗', pinyin: 'lǎng', type: 'character', example: '晴朗。', lesson: '语文园地一', lessonName: '语文园地一', unit: '第一单元', semester: 1 },
        { character: '暴', pinyin: 'bào', type: 'character', example: '暴风。', lesson: '语文园地一', lessonName: '语文园地一', unit: '第一单元', semester: 1 },
        { character: '雷', pinyin: 'léi', type: 'character', example: '雷阵雨。', lesson: '语文园地一', lessonName: '语文园地一', unit: '第一单元', semester: 1 },
        { character: '阵', pinyin: 'zhèn', type: 'character', example: '雷阵雨。', lesson: '语文园地一', lessonName: '语文园地一', unit: '第一单元', semester: 1 },
        { character: '冻', pinyin: 'dòng', type: 'character', example: '霜冻。', lesson: '语文园地一', lessonName: '语文园地一', unit: '第一单元', semester: 1 },
        { character: '夹', pinyin: 'jiā', type: 'character', example: '雨夹雪。', lesson: '语文园地一', lessonName: '语文园地一', unit: '第一单元', semester: 1 },
        
        // 第二单元
        // 识字1《场景歌》
        { character: '鸥', pinyin: 'ōu', type: 'character', example: '一只海鸥。', lesson: '识字1', lessonName: '场景歌', unit: '第二单元', semester: 1 },
        { character: '帆', pinyin: 'fān', type: 'character', example: '一条帆船。', lesson: '识字1', lessonName: '场景歌', unit: '第二单元', semester: 1 },
        { character: '艘', pinyin: 'sōu', type: 'character', example: '一艘军舰。', lesson: '识字1', lessonName: '场景歌', unit: '第二单元', semester: 1 },
        { character: '港', pinyin: 'gǎng', type: 'character', example: '一处港湾。', lesson: '识字1', lessonName: '场景歌', unit: '第二单元', semester: 1 },
        { character: '湾', pinyin: 'wān', type: 'character', example: '一处港湾。', lesson: '识字1', lessonName: '场景歌', unit: '第二单元', semester: 1 },
        { character: '稻', pinyin: 'dào', type: 'character', example: '一块稻田。', lesson: '识字1', lessonName: '场景歌', unit: '第二单元', semester: 1 },
        { character: '行', pinyin: 'háng', type: 'character', example: '一行垂柳。', lesson: '识字1', lessonName: '场景歌', unit: '第二单元', semester: 1 },
        { character: '垂', pinyin: 'chuí', type: 'character', example: '一行垂柳。', lesson: '识字1', lessonName: '场景歌', unit: '第二单元', semester: 1 },
        { character: '园', pinyin: 'yuán', type: 'character', example: '一座花园。', lesson: '识字1', lessonName: '场景歌', unit: '第二单元', semester: 1 },
        { character: '溪', pinyin: 'xī', type: 'character', example: '一道小溪。', lesson: '识字1', lessonName: '场景歌', unit: '第二单元', semester: 1 },
        { character: '丛', pinyin: 'cóng', type: 'character', example: '一丛翠竹。', lesson: '识字1', lessonName: '场景歌', unit: '第二单元', semester: 1 },
        { character: '翠', pinyin: 'cuì', type: 'character', example: '一丛翠竹。', lesson: '识字1', lessonName: '场景歌', unit: '第二单元', semester: 1 },
        { character: '队', pinyin: 'duì', type: 'character', example: '一面队旗。', lesson: '识字1', lessonName: '场景歌', unit: '第二单元', semester: 1 },
        { character: '铜', pinyin: 'tóng', type: 'character', example: '一把铜号。', lesson: '识字1', lessonName: '场景歌', unit: '第二单元', semester: 1 },
        { character: '号', pinyin: 'hào', type: 'character', example: '一把铜号。', lesson: '识字1', lessonName: '场景歌', unit: '第二单元', semester: 1 },
        
        // 识字2《树之歌》
        { character: '榕', pinyin: 'róng', type: 'character', example: '榕树壮。', lesson: '识字2', lessonName: '树之歌', unit: '第二单元', semester: 1 },
        { character: '梧', pinyin: 'wú', type: 'character', example: '梧桐树叶像手掌。', lesson: '识字2', lessonName: '树之歌', unit: '第二单元', semester: 1 },
        { character: '桐', pinyin: 'tóng', type: 'character', example: '梧桐树叶像手掌。', lesson: '识字2', lessonName: '树之歌', unit: '第二单元', semester: 1 },
        { character: '掌', pinyin: 'zhǎng', type: 'character', example: '梧桐树叶像手掌。', lesson: '识字2', lessonName: '树之歌', unit: '第二单元', semester: 1 },
        { character: '枫', pinyin: 'fēng', type: 'character', example: '枫树秋天叶儿红。', lesson: '识字2', lessonName: '树之歌', unit: '第二单元', semester: 1 },
        { character: '松', pinyin: 'sōng', type: 'character', example: '松柏四季披绿装。', lesson: '识字2', lessonName: '树之歌', unit: '第二单元', semester: 1 },
        { character: '柏', pinyin: 'bǎi', type: 'character', example: '松柏四季披绿装。', lesson: '识字2', lessonName: '树之歌', unit: '第二单元', semester: 1 },
        { character: '季', pinyin: 'jì', type: 'character', example: '松柏四季披绿装。', lesson: '识字2', lessonName: '树之歌', unit: '第二单元', semester: 1 },
        { character: '装', pinyin: 'zhuāng', type: 'character', example: '松柏四季披绿装。', lesson: '识字2', lessonName: '树之歌', unit: '第二单元', semester: 1 },
        { character: '桦', pinyin: 'huà', type: 'character', example: '桦树耐寒守北疆。', lesson: '识字2', lessonName: '树之歌', unit: '第二单元', semester: 1 },
        { character: '守', pinyin: 'shǒu', type: 'character', example: '桦树耐寒守北疆。', lesson: '识字2', lessonName: '树之歌', unit: '第二单元', semester: 1 },
        { character: '银', pinyin: 'yín', type: 'character', example: '银杏水杉活化石。', lesson: '识字2', lessonName: '树之歌', unit: '第二单元', semester: 1 },
        { character: '杉', pinyin: 'shān', type: 'character', example: '银杏水杉活化石。', lesson: '识字2', lessonName: '树之歌', unit: '第二单元', semester: 1 },
        { character: '化', pinyin: 'huà', type: 'character', example: '银杏水杉活化石。', lesson: '识字2', lessonName: '树之歌', unit: '第二单元', semester: 1 },
        { character: '桂', pinyin: 'guì', type: 'character', example: '金桂开花满院香。', lesson: '识字2', lessonName: '树之歌', unit: '第二单元', semester: 1 },
        
        // 识字3《拍手歌》
        { character: '世', pinyin: 'shì', type: 'character', example: '动物世界很新奇。', lesson: '识字3', lessonName: '拍手歌', unit: '第二单元', semester: 1 },
        { character: '界', pinyin: 'jiè', type: 'character', example: '动物世界很新奇。', lesson: '识字3', lessonName: '拍手歌', unit: '第二单元', semester: 1 },
        { character: '孔', pinyin: 'kǒng', type: 'character', example: '孔雀锦鸡是伙伴儿。', lesson: '识字3', lessonName: '拍手歌', unit: '第二单元', semester: 1 },
        { character: '雀', pinyin: 'què', type: 'character', example: '孔雀锦鸡是伙伴儿。', lesson: '识字3', lessonName: '拍手歌', unit: '第二单元', semester: 1 },
        { character: '锦', pinyin: 'jǐn', type: 'character', example: '锦鸡是伙伴儿。', lesson: '识字3', lessonName: '拍手歌', unit: '第二单元', semester: 1 },
        { character: '雄', pinyin: 'xióng', type: 'character', example: '雄鹰飞翔云彩间。', lesson: '识字3', lessonName: '拍手歌', unit: '第二单元', semester: 1 },
        { character: '鹰', pinyin: 'yīng', type: 'character', example: '雄鹰飞翔云彩间。', lesson: '识字3', lessonName: '拍手歌', unit: '第二单元', semester: 1 },
        { character: '翔', pinyin: 'xiáng', type: 'character', example: '雄鹰飞翔云彩间。', lesson: '识字3', lessonName: '拍手歌', unit: '第二单元', semester: 1 },
        { character: '雁', pinyin: 'yàn', type: 'character', example: '天空雁群会写字。', lesson: '识字3', lessonName: '拍手歌', unit: '第二单元', semester: 1 },
        { character: '深', pinyin: 'shēn', type: 'character', example: '丛林深处有猛虎。', lesson: '识字3', lessonName: '拍手歌', unit: '第二单元', semester: 1 },
        { character: '猛', pinyin: 'měng', type: 'character', example: '丛林深处有猛虎。', lesson: '识字3', lessonName: '拍手歌', unit: '第二单元', semester: 1 },
        { character: '灵', pinyin: 'líng', type: 'character', example: '黄鹂百灵唱不停。', lesson: '识字3', lessonName: '拍手歌', unit: '第二单元', semester: 1 },
        { character: '休', pinyin: 'xiū', type: 'character', example: '识字表列出生字。', lesson: '识字3', lessonName: '拍手歌', unit: '第二单元', semester: 1 },
        { character: '嬉', pinyin: 'xī', type: 'character', example: '竹林熊猫在嬉戏。', lesson: '识字3', lessonName: '拍手歌', unit: '第二单元', semester: 1 },
        
        // 识字4《田家四季歌》
        { character: '蝴', pinyin: 'hú', type: 'character', example: '花开草长蝴蝶飞。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        { character: '蝶', pinyin: 'dié', type: 'character', example: '花开草长蝴蝶飞。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        { character: '麦', pinyin: 'mài', type: 'character', example: '麦苗儿多嫩。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        { character: '桑', pinyin: 'sāng', type: 'character', example: '桑叶儿正肥。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        { character: '肥', pinyin: 'féi', type: 'character', example: '桑叶儿正肥。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        { character: '农', pinyin: 'nóng', type: 'character', example: '夏季里，农事忙。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        { character: '勤', pinyin: 'qín', type: 'character', example: '早起勤耕作。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        { character: '归', pinyin: 'guī', type: 'character', example: '归来戴月光。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        { character: '戴', pinyin: 'dài', type: 'character', example: '归来戴月光。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        { character: '场', pinyin: 'cháng', type: 'character', example: '秋季里，稻上场。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        { character: '谷', pinyin: 'gǔ', type: 'character', example: '谷像黄金粒粒香。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        { character: '粒', pinyin: 'lì', type: 'character', example: '谷像黄金粒粒香。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        { character: '虽', pinyin: 'suī', type: 'character', example: '身体虽辛苦。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        { character: '辛', pinyin: 'xīn', type: 'character', example: '身体虽辛苦。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        { character: '苦', pinyin: 'kǔ', type: 'character', example: '身体虽辛苦。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        { character: '制', pinyin: 'zhì', type: 'character', example: '新制棉衣暖又轻。', lesson: '识字4', lessonName: '田家四季歌', unit: '第二单元', semester: 1 },
        
        // 语文园地二
        { character: '稀', pinyin: 'xī', type: 'character', example: '密对稀。', lesson: '语文园地二', lessonName: '语文园地二', unit: '第二单元', semester: 1 },
        { character: '菊', pinyin: 'jú', type: 'character', example: '霜菊瘦。', lesson: '语文园地二', lessonName: '语文园地二', unit: '第二单元', semester: 1 },
        { character: '瘦', pinyin: 'shòu', type: 'character', example: '霜菊瘦。', lesson: '语文园地二', lessonName: '语文园地二', unit: '第二单元', semester: 1 },
        { character: '梅', pinyin: 'méi', type: 'character', example: '雨梅肥。', lesson: '语文园地二', lessonName: '语文园地二', unit: '第二单元', semester: 1 },
        { character: '绣', pinyin: 'xiù', type: 'character', example: '晚霞舒锦绣。', lesson: '语文园地二', lessonName: '语文园地二', unit: '第二单元', semester: 1 },
        { character: '缀', pinyin: 'zhuì', type: 'character', example: '朝露缀珠玑。', lesson: '语文园地二', lessonName: '语文园地二', unit: '第二单元', semester: 1 },
        { character: '牧', pinyin: 'mù', type: 'character', example: '牧童骑黄牛。', lesson: '语文园地二', lessonName: '语文园地二', unit: '第二单元', semester: 1 },
        
        // 第三单元
        // 第4课《彩虹》
        { character: '虹', pinyin: 'hóng', type: 'character', example: '天上有一座美丽的彩虹桥。', lesson: '第4课', lessonName: '彩虹', unit: '第三单元', semester: 1 },
        { character: '浇', pinyin: 'jiāo', type: 'character', example: '爸爸，您浇花用的那把水壶呢？', lesson: '第4课', lessonName: '彩虹', unit: '第三单元', semester: 1 },
        { character: '壶', pinyin: 'hú', type: 'character', example: '爸爸，您浇花用的那把水壶呢？', lesson: '第4课', lessonName: '彩虹', unit: '第三单元', semester: 1 },
        { character: '提', pinyin: 'tí', type: 'character', example: '如果我提着它。', lesson: '第4课', lessonName: '彩虹', unit: '第三单元', semester: 1 },
        { character: '洒', pinyin: 'sǎ', type: 'character', example: '把水洒下来。', lesson: '第4课', lessonName: '彩虹', unit: '第三单元', semester: 1 },
        { character: '挑', pinyin: 'tiāo', type: 'character', example: '挑水去洗田。', lesson: '第4课', lessonName: '彩虹', unit: '第三单元', semester: 1 },
        { character: '拿', pinyin: 'ná', type: 'character', example: '如果我拿着它。', lesson: '第4课', lessonName: '彩虹', unit: '第三单元', semester: 1 },
        { character: '系', pinyin: 'jì', type: 'character', example: '你系在门前树上的秋千呢？', lesson: '第4课', lessonName: '彩虹', unit: '第三单元', semester: 1 },
        { character: '荡', pinyin: 'dàng', type: 'character', example: '坐着秋千荡来荡去。', lesson: '第4课', lessonName: '彩虹', unit: '第三单元', semester: 1 },
        { character: '裙', pinyin: 'qún', type: 'character', example: '花裙子飘啊飘的。', lesson: '第4课', lessonName: '彩虹', unit: '第三单元', semester: 1 },
        
        // 第5课《玲玲的画》
        { character: '玲', pinyin: 'líng', type: 'character', example: '玲玲得意地端详着自己画的。', lesson: '第5课', lessonName: '玲玲的画', unit: '第三单元', semester: 1 },
        { character: '详', pinyin: 'xiáng', type: 'character', example: '玲玲得意地端详着自己画的。', lesson: '第5课', lessonName: '玲玲的画', unit: '第三单元', semester: 1 },
        { character: '幅', pinyin: 'fú', type: 'character', example: '这幅画明天就要参加评奖了。', lesson: '第5课', lessonName: '玲玲的画', unit: '第三单元', semester: 1 },
        { character: '评', pinyin: 'píng', type: 'character', example: '参加评奖了。', lesson: '第5课', lessonName: '玲玲的画', unit: '第三单元', semester: 1 },
        { character: '奖', pinyin: 'jiǎng', type: 'character', example: '参加评奖了。', lesson: '第5课', lessonName: '玲玲的画', unit: '第三单元', semester: 1 },
        { character: '脏', pinyin: 'zāng', type: 'character', example: '把画弄脏了。', lesson: '第5课', lessonName: '玲玲的画', unit: '第三单元', semester: 1 },
        { character: '伤', pinyin: 'shāng', type: 'character', example: '玲玲伤心地哭了起来。', lesson: '第5课', lessonName: '玲玲的画', unit: '第三单元', semester: 1 },
        { character: '报', pinyin: 'bào', type: 'character', example: '爸爸放下报纸问。', lesson: '第5课', lessonName: '玲玲的画', unit: '第三单元', semester: 1 },
        { character: '另', pinyin: 'lìng', type: 'character', example: '另画一张也来不及了。', lesson: '第5课', lessonName: '玲玲的画', unit: '第三单元', semester: 1 },
        { character: '及', pinyin: 'jí', type: 'character', example: '另画一张也来不及了。', lesson: '第5课', lessonName: '玲玲的画', unit: '第三单元', semester: 1 },
        { character: '懒', pinyin: 'lǎn', type: 'character', example: '小花狗懒洋洋地趴在楼梯上。', lesson: '第5课', lessonName: '玲玲的画', unit: '第三单元', semester: 1 },
        { character: '整', pinyin: 'zhěng', type: 'character', example: '整张画看上去更好了。', lesson: '第5课', lessonName: '玲玲的画', unit: '第三单元', semester: 1 },
        { character: '并', pinyin: 'bìng', type: 'character', example: '并不像我们想象的那么糟。', lesson: '第5课', lessonName: '玲玲的画', unit: '第三单元', semester: 1 },
        { character: '糟', pinyin: 'zāo', type: 'character', example: '并不像我们想象的那么糟。', lesson: '第5课', lessonName: '玲玲的画', unit: '第三单元', semester: 1 },
        { character: '肯', pinyin: 'kěn', type: 'character', example: '只要肯动脑筋。', lesson: '第5课', lessonName: '玲玲的画', unit: '第三单元', semester: 1 },
        
        // 第6课《去外婆家》
        { character: '婆', pinyin: 'pó', type: 'character', example: '外婆家在山脚下。', lesson: '第6课', lessonName: '去外婆家', unit: '第三单元', semester: 1 },
        { character: '最', pinyin: 'zuì', type: 'character', example: '我最大的乐趣就是去外婆家。', lesson: '第6课', lessonName: '去外婆家', unit: '第三单元', semester: 1 },
        { character: '趣', pinyin: 'qù', type: 'character', example: '我最大的乐趣就是去外婆家。', lesson: '第6课', lessonName: '去外婆家', unit: '第三单元', semester: 1 },
        { character: '宝', pinyin: 'bǎo', type: 'character', example: '山上山下宝贝多。', lesson: '第6课', lessonName: '去外婆家', unit: '第三单元', semester: 1 },
        { character: '些', pinyin: 'xiē', type: 'character', example: '带一些山楂。', lesson: '第6课', lessonName: '去外婆家', unit: '第三单元', semester: 1 },
        { character: '或', pinyin: 'huò', type: 'character', example: '或者别在衣服上。', lesson: '第6课', lessonName: '去外婆家', unit: '第三单元', semester: 1 },
        { character: '留', pinyin: 'liú', type: 'character', example: '外婆总要给我留一份。', lesson: '第6课', lessonName: '去外婆家', unit: '第三单元', semester: 1 },
        { character: '份', pinyin: 'fèn', type: 'character', example: '外婆总要给我留一份。', lesson: '第6课', lessonName: '去外婆家', unit: '第三单元', semester: 1 },
        { character: '喂', pinyin: 'wèi', type: 'character', example: '从小喂大的山雀。', lesson: '第6课', lessonName: '去外婆家', unit: '第三单元', semester: 1 },
        { character: '曲', pinyin: 'qǔ', type: 'character', example: '唱着曲儿给你听。', lesson: '第6课', lessonName: '去外婆家', unit: '第三单元', semester: 1 },
        { character: '杜', pinyin: 'dù', type: 'character', example: '开满了杜鹃花。', lesson: '第6课', lessonName: '去外婆家', unit: '第三单元', semester: 1 },
        { character: '鹃', pinyin: 'juān', type: 'character', example: '开满了杜鹃花。', lesson: '第6课', lessonName: '去外婆家', unit: '第三单元', semester: 1 },
        { character: '名', pinyin: 'míng', type: 'character', example: '说不出名字的野花。', lesson: '第6课', lessonName: '去外婆家', unit: '第三单元', semester: 1 },
        { character: '者', pinyin: 'zhě', type: 'character', example: '或者别在衣服上。', lesson: '第6课', lessonName: '去外婆家', unit: '第三单元', semester: 1 },
        { character: '扑', pinyin: 'pū', type: 'character', example: '香气扑鼻。', lesson: '第6课', lessonName: '去外婆家', unit: '第三单元', semester: 1 },
        
        // 语文园地三
        { character: '弹', pinyin: 'tán', type: 'character', example: '弹钢琴。', lesson: '语文园地三', lessonName: '语文园地三', unit: '第三单元', semester: 1 },
        { character: '钢', pinyin: 'gāng', type: 'character', example: '弹钢琴。', lesson: '语文园地三', lessonName: '语文园地三', unit: '第三单元', semester: 1 },
        { character: '琴', pinyin: 'qín', type: 'character', example: '弹钢琴。', lesson: '语文园地三', lessonName: '语文园地三', unit: '第三单元', semester: 1 },
        { character: '练', pinyin: 'liàn', type: 'character', example: '练舞蹈。', lesson: '语文园地三', lessonName: '语文园地三', unit: '第三单元', semester: 1 },
        { character: '团', pinyin: 'tuán', type: 'character', example: '纸团。', lesson: '语文园地三', lessonName: '语文园地三', unit: '第三单元', semester: 1 },
        { character: '泥', pinyin: 'ní', type: 'character', example: '捏泥人。', lesson: '语文园地三', lessonName: '语文园地三', unit: '第三单元', semester: 1 },
        { character: '围', pinyin: 'wéi', type: 'character', example: '下围棋。', lesson: '语文园地三', lessonName: '语文园地三', unit: '第三单元', semester: 1 },
        { character: '滚', pinyin: 'gǔn', type: 'character', example: '滚铁环。', lesson: '语文园地三', lessonName: '语文园地三', unit: '第三单元', semester: 1 },
        { character: '铁', pinyin: 'tiě', type: 'character', example: '滚铁环。', lesson: '语文园地三', lessonName: '语文园地三', unit: '第三单元', semester: 1 },
        { character: '环', pinyin: 'huán', type: 'character', example: '滚铁环。', lesson: '语文园地三', lessonName: '语文园地三', unit: '第三单元', semester: 1 },
        { character: '滑', pinyin: 'huá', type: 'character', example: '滑滑梯。', lesson: '语文园地三', lessonName: '语文园地三', unit: '第三单元', semester: 1 },
        { character: '梯', pinyin: 'tī', type: 'character', example: '滑滑梯。', lesson: '语文园地三', lessonName: '语文园地三', unit: '第三单元', semester: 1 },
        
        // 第四单元
        // 第7课《古诗二首》
        { character: '登', pinyin: 'dēng', type: 'character', example: '登鹳雀楼。', lesson: '第7课', lessonName: '古诗二首', unit: '第四单元', semester: 1 },
        { character: '唐', pinyin: 'táng', type: 'character', example: '唐代诗人。', lesson: '第7课', lessonName: '古诗二首', unit: '第四单元', semester: 1 },
        { character: '依', pinyin: 'yī', type: 'character', example: '白日依山尽。', lesson: '第7课', lessonName: '古诗二首', unit: '第四单元', semester: 1 },
        { character: '尽', pinyin: 'jìn', type: 'character', example: '白日依山尽。', lesson: '第7课', lessonName: '古诗二首', unit: '第四单元', semester: 1 },
        { character: '欲', pinyin: 'yù', type: 'character', example: '欲穷千里目。', lesson: '第7课', lessonName: '古诗二首', unit: '第四单元', semester: 1 },
        { character: '穷', pinyin: 'qióng', type: 'character', example: '欲穷千里目。', lesson: '第7课', lessonName: '古诗二首', unit: '第四单元', semester: 1 },
        { character: '层', pinyin: 'céng', type: 'character', example: '更上一层楼。', lesson: '第7课', lessonName: '古诗二首', unit: '第四单元', semester: 1 },
        { character: '瀑', pinyin: 'pù', type: 'character', example: '望庐山瀑布。', lesson: '第7课', lessonName: '古诗二首', unit: '第四单元', semester: 1 },
        { character: '布', pinyin: 'bù', type: 'character', example: '望庐山瀑布。', lesson: '第7课', lessonName: '古诗二首', unit: '第四单元', semester: 1 },
        { character: '炉', pinyin: 'lú', type: 'character', example: '日照香炉生紫烟。', lesson: '第7课', lessonName: '古诗二首', unit: '第四单元', semester: 1 },
        { character: '紫', pinyin: 'zǐ', type: 'character', example: '生紫烟。', lesson: '第7课', lessonName: '古诗二首', unit: '第四单元', semester: 1 },
        { character: '烟', pinyin: 'yān', type: 'character', example: '生紫烟。', lesson: '第7课', lessonName: '古诗二首', unit: '第四单元', semester: 1 },
        { character: '遥', pinyin: 'yáo', type: 'character', example: '遥看瀑布挂前川。', lesson: '第7课', lessonName: '古诗二首', unit: '第四单元', semester: 1 },
        { character: '尺', pinyin: 'chǐ', type: 'character', example: '飞流直下三千尺。', lesson: '第7课', lessonName: '古诗二首', unit: '第四单元', semester: 1 },
        
        // 第8课《黄山奇石》
        { character: '闻', pinyin: 'wén', type: 'character', example: '中外闻名的黄山风景区。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        { character: '景', pinyin: 'jǐng', type: 'character', example: '中外闻名的黄山风景区。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        { character: '区', pinyin: 'qū', type: 'character', example: '中外闻名的黄山风景区。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        { character: '省', pinyin: 'shěng', type: 'character', example: '在我国安徽省南部。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        { character: '部', pinyin: 'bù', type: 'character', example: '安徽省南部。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        { character: '秀', pinyin: 'xiù', type: 'character', example: '那里景色秀丽神奇。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        { character: '神', pinyin: 'shén', type: 'character', example: '景色秀丽神奇。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        { character: '仙', pinyin: 'xiān', type: 'character', example: '"仙人指路"。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        { character: '盘', pinyin: 'pán', type: 'character', example: '落在山顶的石盘上。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        { character: '指', pinyin: 'zhǐ', type: 'character', example: '"仙人指路"。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        { character: '巨', pinyin: 'jù', type: 'character', example: '那块巨石真像一位仙人。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        { character: '位', pinyin: 'wèi', type: 'character', example: '那块巨石真像一位仙人。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        { character: '伸', pinyin: 'shēn', type: 'character', example: '伸着手臂。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        { character: '都', pinyin: 'dū', type: 'character', example: '天都峰。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        { character: '著', pinyin: 'zhù', type: 'character', example: '著名。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        { character: '抢', pinyin: 'qiǎng', type: 'character', example: '狮子抢球。', lesson: '第8课', lessonName: '黄山奇石', unit: '第四单元', semester: 1 },
        
        // 第9课《日月潭》
        { character: '潭', pinyin: 'tán', type: 'character', example: '日月潭是我国台湾省最大的一个湖。', lesson: '第9课', lessonName: '日月潭', unit: '第四单元', semester: 1 },
        { character: '绕', pinyin: 'rào', type: 'character', example: '群山环绕。', lesson: '第9课', lessonName: '日月潭', unit: '第四单元', semester: 1 },
        { character: '茂', pinyin: 'mào', type: 'character', example: '树木茂盛。', lesson: '第9课', lessonName: '日月潭', unit: '第四单元', semester: 1 },
        { character: '盛', pinyin: 'shèng', type: 'character', example: '树木茂盛。', lesson: '第9课', lessonName: '日月潭', unit: '第四单元', semester: 1 },
        { character: '胜', pinyin: 'shèng', type: 'character', example: '名胜古迹。', lesson: '第9课', lessonName: '日月潭', unit: '第四单元', semester: 1 },
        { character: '央', pinyin: 'yāng', type: 'character', example: '湖中央有个美丽的小岛。', lesson: '第9课', lessonName: '日月潭', unit: '第四单元', semester: 1 },
        { character: '岛', pinyin: 'dǎo', type: 'character', example: '美丽的小岛。', lesson: '第9课', lessonName: '日月潭', unit: '第四单元', semester: 1 },
        { character: '隐', pinyin: 'yǐn', type: 'character', example: '隐隐约约地倒映在湖水中。', lesson: '第9课', lessonName: '日月潭', unit: '第四单元', semester: 1 },
        { character: '约', pinyin: 'yuē', type: 'character', example: '隐隐约约地倒映在湖水中。', lesson: '第9课', lessonName: '日月潭', unit: '第四单元', semester: 1 },
        { character: '倒', pinyin: 'dǎo', type: 'character', example: '倒映在湖水中。', lesson: '第9课', lessonName: '日月潭', unit: '第四单元', semester: 1 },
        { character: '映', pinyin: 'yìng', type: 'character', example: '倒映在湖水中。', lesson: '第9课', lessonName: '日月潭', unit: '第四单元', semester: 1 },
        { character: '童', pinyin: 'tóng', type: 'character', example: '就像童话中的仙境。', lesson: '第9课', lessonName: '日月潭', unit: '第四单元', semester: 1 },
        { character: '吸', pinyin: 'xī', type: 'character', example: '吸引了许许多多的游客。', lesson: '第9课', lessonName: '日月潭', unit: '第四单元', semester: 1 },
        { character: '引', pinyin: 'yǐn', type: 'character', example: '吸引了许许多多的游客。', lesson: '第9课', lessonName: '日月潭', unit: '第四单元', semester: 1 },
        { character: '客', pinyin: 'kè', type: 'character', example: '中外游客。', lesson: '第9课', lessonName: '日月潭', unit: '第四单元', semester: 1 },
        
        // 第10课《葡萄沟》
        { character: '葡', pinyin: 'pú', type: 'character', example: '新疆吐鲁番有个地方叫葡萄沟。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '萄', pinyin: 'táo', type: 'character', example: '新疆吐鲁番有个地方叫葡萄沟。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '沟', pinyin: 'gōu', type: 'character', example: '新疆吐鲁番有个地方叫葡萄沟。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '熟', pinyin: 'shú', type: 'character', example: '葡萄成熟了。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '坡', pinyin: 'pō', type: 'character', example: '葡萄种在山坡的梯田上。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '密', pinyin: 'mì', type: 'character', example: '茂密的枝叶向四面展开。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '枝', pinyin: 'zhī', type: 'character', example: '茂密的枝叶。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '淡', pinyin: 'dàn', type: 'character', example: '有红的、白的、紫的、淡绿的。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '好', pinyin: 'hào', type: 'character', example: '好客的维吾尔族老乡。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '族', pinyin: 'zú', type: 'character', example: '好客的维吾尔族老乡。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '够', pinyin: 'gòu', type: 'character', example: '让你吃个够。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '收', pinyin: 'shōu', type: 'character', example: '收下来的葡萄。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '干', pinyin: 'gān', type: 'character', example: '制成葡萄干。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '修', pinyin: 'xiū', type: 'character', example: '晾房修在山坡上。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '钉', pinyin: 'dìng', type: 'character', example: '里面钉着许多木架子。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '颜', pinyin: 'yán', type: 'character', example: '颜色鲜，味道甜。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        { character: '味', pinyin: 'wèi', type: 'character', example: '颜色鲜，味道甜。', lesson: '第10课', lessonName: '葡萄沟', unit: '第四单元', semester: 1 },
        
        // 语文园地四
        { character: '检', pinyin: 'jiǎn', type: 'character', example: '检票。', lesson: '语文园地四', lessonName: '语文园地四', unit: '第四单元', semester: 1 },
        { character: '丰', pinyin: 'fēng', type: 'character', example: '丰昌站。', lesson: '语文园地四', lessonName: '语文园地四', unit: '第四单元', semester: 1 },
        { character: '昌', pinyin: 'chāng', type: 'character', example: '丰昌站。', lesson: '语文园地四', lessonName: '语文园地四', unit: '第四单元', semester: 1 },
        { character: '铺', pinyin: 'pù', type: 'character', example: '上铺。', lesson: '语文园地四', lessonName: '语文园地四', unit: '第四单元', semester: 1 },
        { character: '惠', pinyin: 'huì', type: 'character', example: '优惠。', lesson: '语文园地四', lessonName: '语文园地四', unit: '第四单元', semester: 1 },
        { character: '卧', pinyin: 'wò', type: 'character', example: '卧铺。', lesson: '语文园地四', lessonName: '语文园地四', unit: '第四单元', semester: 1 },
        { character: '仅', pinyin: 'jǐn', type: 'character', example: '仅供报销使用。', lesson: '语文园地四', lessonName: '语文园地四', unit: '第四单元', semester: 1 },
        { character: '供', pinyin: 'gōng', type: 'character', example: '仅供报销使用。', lesson: '语文园地四', lessonName: '语文园地四', unit: '第四单元', semester: 1 },
        { character: '销', pinyin: 'xiāo', type: 'character', example: '仅供报销使用。', lesson: '语文园地四', lessonName: '语文园地四', unit: '第四单元', semester: 1 },
        { character: '使', pinyin: 'shǐ', type: 'character', example: '仅供报销使用。', lesson: '语文园地四', lessonName: '语文园地四', unit: '第四单元', semester: 1 },
        
        // 第五单元
        // 第11课《坐井观天》
        { character: '沿', pinyin: 'yán', type: 'character', example: '落在井沿上。', lesson: '第11课', lessonName: '坐井观天', unit: '第五单元', semester: 1 },
        { character: '渴', pinyin: 'kě', type: 'character', example: '口渴了。', lesson: '第11课', lessonName: '坐井观天', unit: '第五单元', semester: 1 },
        { character: '喝', pinyin: 'hē', type: 'character', example: '找点儿水喝。', lesson: '第11课', lessonName: '坐井观天', unit: '第五单元', semester: 1 },
        { character: '弄', pinyin: 'nòng', type: 'character', example: '你弄错了。', lesson: '第11课', lessonName: '坐井观天', unit: '第五单元', semester: 1 },
        { character: '错', pinyin: 'cuò', type: 'character', example: '你弄错了。', lesson: '第11课', lessonName: '坐井观天', unit: '第五单元', semester: 1 },
        { character: '际', pinyin: 'jì', type: 'character', example: '天无边无际。', lesson: '第11课', lessonName: '坐井观天', unit: '第五单元', semester: 1 },
        
        // 第12课《寒号鸟》
        { character: '当', pinyin: 'dàng', type: 'character', example: '把这道缝当作自己的窝。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        { character: '鹊', pinyin: 'què', type: 'character', example: '喜鹊住在对面。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        { character: '寻', pinyin: 'xún', type: 'character', example: '东寻西找。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        { character: '枯', pinyin: 'kū', type: 'character', example: '一些枯草。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        { character: '却', pinyin: 'què', type: 'character', example: '寒号鸟却只知道出去玩。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        { character: '累', pinyin: 'lèi', type: 'character', example: '累了就回来睡觉。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        { character: '劝', pinyin: 'quàn', type: 'character', example: '喜鹊来到崖缝前劝寒号鸟。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        { character: '刮', pinyin: 'guā', type: 'character', example: '寒风呼呼地刮着。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        { character: '死', pinyin: 'sǐ', type: 'character', example: '寒风冻死我。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        { character: '将', pinyin: 'jiāng', type: 'character', example: '将来难过。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        { character: '且', pinyin: 'qiě', type: 'character', example: '得过且过。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        { character: '狂', pinyin: 'kuáng', type: 'character', example: '北风像狮子一样狂吼。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        { character: '冷', pinyin: 'lěng', type: 'character', example: '崖缝里冷得像冰窖。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        { character: '重', pinyin: 'chóng', type: 'character', example: '寒号鸟重复着哀号。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        { character: '复', pinyin: 'fù', type: 'character', example: '寒号鸟重复着哀号。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        { character: '哀', pinyin: 'āi', type: 'character', example: '哀号。', lesson: '第12课', lessonName: '寒号鸟', unit: '第五单元', semester: 1 },
        
        // 第13课《我要的是葫芦》
        { character: '葫', pinyin: 'hú', type: 'character', example: '从前，有个人种了一棵葫芦。', lesson: '第13课', lessonName: '我要的是葫芦', unit: '第五单元', semester: 1 },
        { character: '芦', pinyin: 'lú', type: 'character', example: '从前，有个人种了一棵葫芦。', lesson: '第13课', lessonName: '我要的是葫芦', unit: '第五单元', semester: 1 },
        { character: '藤', pinyin: 'téng', type: 'character', example: '细长的葫芦藤上长满了绿叶。', lesson: '第13课', lessonName: '我要的是葫芦', unit: '第五单元', semester: 1 },
        { character: '盯', pinyin: 'dīng', type: 'character', example: '他盯着小葫芦自言自语地。', lesson: '第13课', lessonName: '我要的是葫芦', unit: '第五单元', semester: 1 },
        { character: '赛', pinyin: 'sài', type: 'character', example: '长得赛过大南瓜才好呢！', lesson: '第13课', lessonName: '我要的是葫芦', unit: '第五单元', semester: 1 },
        { character: '怪', pinyin: 'guài', type: 'character', example: '那个人感到很奇怪。', lesson: '第13课', lessonName: '我要的是葫芦', unit: '第五单元', semester: 1 },
        { character: '慢', pinyin: 'màn', type: 'character', example: '小葫芦慢慢地变黄了。', lesson: '第13课', lessonName: '我要的是葫芦', unit: '第五单元', semester: 1 },
        { character: '变', pinyin: 'biàn', type: 'character', example: '小葫芦慢慢地变黄了。', lesson: '第13课', lessonName: '我要的是葫芦', unit: '第五单元', semester: 1 },
        
        // 语文园地五
        { character: '轿', pinyin: 'jiào', type: 'character', example: '轿车。', lesson: '语文园地五', lessonName: '语文园地五', unit: '第五单元', semester: 1 },
        { character: '救', pinyin: 'jiù', type: 'character', example: '救护车。', lesson: '语文园地五', lessonName: '语文园地五', unit: '第五单元', semester: 1 },
        { character: '摩', pinyin: 'mó', type: 'character', example: '摩托车。', lesson: '语文园地五', lessonName: '语文园地五', unit: '第五单元', semester: 1 },
        { character: '托', pinyin: 'tuō', type: 'character', example: '摩托车。', lesson: '语文园地五', lessonName: '语文园地五', unit: '第五单元', semester: 1 },
        { character: '防', pinyin: 'fáng', type: 'character', example: '防火。', lesson: '语文园地五', lessonName: '语文园地五', unit: '第五单元', semester: 1 },
        { character: '渔', pinyin: 'yú', type: 'character', example: '渔船。', lesson: '语文园地五', lessonName: '语文园地五', unit: '第五单元', semester: 1 },
        { character: '货', pinyin: 'huò', type: 'character', example: '货船。', lesson: '语文园地五', lessonName: '语文园地五', unit: '第五单元', semester: 1 },
        { character: '科', pinyin: 'kē', type: 'character', example: '科学考察船。', lesson: '语文园地五', lessonName: '语文园地五', unit: '第五单元', semester: 1 },
        { character: '考', pinyin: 'kǎo', type: 'character', example: '科学考察船。', lesson: '语文园地五', lessonName: '语文园地五', unit: '第五单元', semester: 1 },
        { character: '察', pinyin: 'chá', type: 'character', example: '科学考察船。', lesson: '语文园地五', lessonName: '语文园地五', unit: '第五单元', semester: 1 },
        
        // 第六单元
        // 第14课《八角楼上》
        { character: '楼', pinyin: 'lóu', type: 'character', example: '八角楼上。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 },
        { character: '艰', pinyin: 'jiān', type: 'character', example: '艰苦斗争的年代。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 },
        { character: '斗', pinyin: 'dòu', type: 'character', example: '艰苦斗争的年代。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 },
        { character: '代', pinyin: 'dài', type: 'character', example: '艰苦斗争的年代。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 },
        { character: '临', pinyin: 'lín', type: 'character', example: '每当夜幕降临的时候。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 },
        { character: '腊', pinyin: 'là', type: 'character', example: '这是个寒冬腊月的深夜。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 },
        { character: '薄', pinyin: 'báo', type: 'character', example: '披着薄毯子。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 },
        { character: '毯', pinyin: 'tǎn', type: 'character', example: '披着薄毯子。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 },
        { character: '章', pinyin: 'zhāng', type: 'character', example: '毛主席在写文章。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 },
        { character: '握', pinyin: 'wò', type: 'character', example: '握着笔。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 },
        { character: '凝', pinyin: 'níng', type: 'character', example: '凝视着这星星之火。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 },
        { character: '觉', pinyin: 'jué', type: 'character', example: '察觉到。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 },
        { character: '油', pinyin: 'yóu', type: 'character', example: '在这盏清油灯下。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 },
        { character: '辉', pinyin: 'huī', type: 'character', example: '光辉著作。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 },
        { character: '革', pinyin: 'gé', type: 'character', example: '照亮了中国革命胜利的道路。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 },
        { character: '利', pinyin: 'lì', type: 'character', example: '照亮了中国革命胜利的道路。', lesson: '第14课', lessonName: '八角楼上', unit: '第六单元', semester: 1 }
    ],
    
    // 下学期数据（占位 - 待补充）
    semester2: []
};
